### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by benkoshy** [TSFoster/elm-sha1#9]
Hi there

I'm having trouble running the tests. Perhaps i'm doing something wrong? Here are my steps:

- cloned the repository.
- ran `elm make`
- installed elm-test
- then when i run `elm-test' I get this error:

```terminal
-- MODULE NOT FOUND - /home/koshy/Documents/www/elm_projects/elm-sha1/tests/Tests.elm

You are trying to import a `Generated.SHA1LongMsg` module:

8| import Generated.SHA1LongMsg as Long
          ^^^^^^^^^^^^^^^^^^^^^
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?

    Test.Html.Event
    Test.Html.Query
    Test.Html.Selector
    Bytes.Decode

Hint: If it is not a typo, check the "dependencies" and "source-directories" of
your elm.json to make sure all the packages you need are listed there!
```

Am I missing a package?

**Comment by TSFoster** [comment]
Ah, I was actually writing a short note to the README about this at almost exactly the same time you created this issue!

You need to run `make test`. This will download the CAVS response files from [here](https://github.com/pyca/cryptography/tree/master/vectors/cryptography_vectors/hashes/SHA1) and generate the tests from them, generate the docs tests with elm-verify-examples, and run elm-format and elm-test.

Let me know if you have any problems getting it to work
